export const successStories = [
  {
    name: "Dr. Priya Sharma",
    username: "@drpriya",
    body: "Our EduTech platform reached 10,000+ rural students. The ₹25L grant transformed education accessibility across 5 states.",
    img: "https://avatar.vercel.sh/priya",
    project: "EduTech Platform",
    impact: "10,000+ Students",
  },
  {
    name: "Rajesh Kumar",
    username: "@rajeshk",
    body: "AgriBot revolutionized farming for 500+ farmers. IoT sensors increased crop yields by 40% with ₹35L funding support.",
    img: "https://avatar.vercel.sh/rajesh",
    project: "AgriBot Solutions",
    impact: "500+ Farmers",
  },
  {
    name: "Dr. Meera Patel",
    username: "@drmeera",
    body: "HealthCare Connect enabled 5,000+ rural consultations. Telemedicine broke geographical barriers with our ₹40L grant.",
    img: "https://avatar.vercel.sh/meera",
    project: "HealthCare Connect",
    impact: "5,000+ Consultations",
  },
  {
    name: "Vikram Singh",
    username: "@vikrams",
    body: "CleanEnergy startup now powers 200+ villages. Solar innovation project scaled with comprehensive incubation support.",
    img: "https://avatar.vercel.sh/vikram",
    project: "CleanEnergy Solutions",
    impact: "200+ Villages",
  },
  {
    name: "Anita Reddy",
    username: "@anitar",
    body: "FinTech platform digitized 1000+ rural businesses. Micro-finance solutions reached underserved communities effectively.",
    img: "https://avatar.vercel.sh/anita",
    project: "Rural FinTech",
    impact: "1000+ Businesses",
  },
  {
    name: "Suresh Gupta",
    username: "@sureshg",
    body: "Water purification tech deployed in 50+ villages. Our innovation saves 10,000+ lives annually with sustainable solutions.",
    img: "https://avatar.vercel.sh/suresh",
    project: "AquaPure Systems",
    impact: "50+ Villages",
  },
];
